# Copyright (c) 2026, Trade Hub and contributors
# For license information, please see license.txt

"""
Trade Hub Utilities Package.

This package contains utility modules for the Trade Hub B2B Trading Platform,
including multi-tenant isolation, fetch_from helpers, and other common utilities.
"""

from tr_tradehub.utils.tenant import (
    get_current_tenant,
    set_tenant_context,
    validate_tenant,
    set_tenant,
    clear_tenant_context,
    get_tenant_settings,
    is_platform_admin,
    tenant_required,
    get_user_tenant,
    check_tenant_permission,
)

from tr_tradehub.utils.fetch_from_helper import (
    manual_fetch_for_child,
    manual_fetch_single_field,
    bulk_fetch_for_children,
    get_fetch_from_config,
    apply_fetch_from_for_doctype,
    generate_fetch_js_handler,
    fetch_linked_values,
    get_child_fetch_config,
    validate_fetch_from_fields,
    ensure_read_only_fetch_fields,
)

from tr_tradehub.utils.erpnext_sync import (
    is_erpnext_installed,
    get_sync_settings,
    sync_seller_to_supplier,
    sync_supplier_to_seller,
    sync_buyer_to_customer,
    sync_customer_to_buyer,
    bulk_sync_sellers_to_suppliers,
    bulk_sync_buyers_to_customers,
    get_sync_status,
    unlink_erpnext_document,
)

from tr_tradehub.utils.freight_calculator import (
    calculate_freight,
    calculate_dimensional_weight,
    calculate_chargeable_weight,
    calculate_insurance_cost,
    calculate_total_shipping_cost,
    get_incoterm_cost_breakdown,
    compare_carrier_rates,
    convert_weight_to_kg,
    convert_dimension_to_cm,
    get_carrier_settings,
)

from tr_tradehub.utils.buybox_algorithm import (
    calculate_buybox_winner,
    get_buybox_winner,
    calculate_entry_scores,
    calculate_price_score,
    calculate_delivery_score,
    calculate_rating_score,
    calculate_stock_score,
    calculate_composite_score,
    bulk_calculate_buybox,
    get_buybox_weights,
    validate_weights,
    simulate_buybox_score,
    get_buybox_algorithm_info,
)

from tr_tradehub.utils.sitemap_generator import (
    generate_sitemap,
    generate_sitemap_index,
    generate_complete_sitemap,
    get_sitemap_xml,
    get_sitemap_index_xml,
    refresh_sitemap,
    get_sitemap_statistics,
    schedule_sitemap_regeneration,
    regenerate_all_sitemaps,
    clear_sitemap_cache,
    invalidate_sitemap_for_doc,
    ping_search_engines,
)

from tr_tradehub.utils.tax_calculator import (
    calculate_tax,
    calculate_tax_for_items,
    get_default_tax_rate,
    get_tax_rate_for_listing,
    get_tax_rate_for_category,
    get_shipping_tax_rate,
    is_b2b_tax_exempt,
    calculate_b2b_tax,
    get_tax_breakdown_for_invoice,
    get_price_display,
    format_tax_amount,
    validate_tax_rate,
    get_suggested_tax_rate,
    TURKISH_VAT_RATES,
)

from tr_tradehub.utils.seller_payout import (
    credit_seller_for_order,
    release_escrow_to_balance,
    process_order_refund_from_balance,
    calculate_commission,
    get_payout_hold_days,
    schedule_escrow_release,
    process_escrow_release,
    process_pending_escrow_releases,
    on_sub_order_completed,
    on_sub_order_refunded,
)

__all__ = [
    # Tenant utilities
    "get_current_tenant",
    "set_tenant_context",
    "validate_tenant",
    "set_tenant",
    "clear_tenant_context",
    "get_tenant_settings",
    "is_platform_admin",
    "tenant_required",
    "get_user_tenant",
    "check_tenant_permission",
    # Fetch from helpers
    "manual_fetch_for_child",
    "manual_fetch_single_field",
    "bulk_fetch_for_children",
    "get_fetch_from_config",
    "apply_fetch_from_for_doctype",
    "generate_fetch_js_handler",
    "fetch_linked_values",
    "get_child_fetch_config",
    "validate_fetch_from_fields",
    "ensure_read_only_fetch_fields",
    # ERPNext sync utilities
    "is_erpnext_installed",
    "get_sync_settings",
    "sync_seller_to_supplier",
    "sync_supplier_to_seller",
    "sync_buyer_to_customer",
    "sync_customer_to_buyer",
    "bulk_sync_sellers_to_suppliers",
    "bulk_sync_buyers_to_customers",
    "get_sync_status",
    "unlink_erpnext_document",
    # Freight calculator utilities
    "calculate_freight",
    "calculate_dimensional_weight",
    "calculate_chargeable_weight",
    "calculate_insurance_cost",
    "calculate_total_shipping_cost",
    "get_incoterm_cost_breakdown",
    "compare_carrier_rates",
    "convert_weight_to_kg",
    "convert_dimension_to_cm",
    "get_carrier_settings",
    # Buy Box algorithm utilities
    "calculate_buybox_winner",
    "get_buybox_winner",
    "calculate_entry_scores",
    "calculate_price_score",
    "calculate_delivery_score",
    "calculate_rating_score",
    "calculate_stock_score",
    "calculate_composite_score",
    "bulk_calculate_buybox",
    "get_buybox_weights",
    "validate_weights",
    "simulate_buybox_score",
    "get_buybox_algorithm_info",
    # Sitemap generator utilities
    "generate_sitemap",
    "generate_sitemap_index",
    "generate_complete_sitemap",
    "get_sitemap_xml",
    "get_sitemap_index_xml",
    "refresh_sitemap",
    "get_sitemap_statistics",
    "schedule_sitemap_regeneration",
    "regenerate_all_sitemaps",
    "clear_sitemap_cache",
    "invalidate_sitemap_for_doc",
    "ping_search_engines",
    # Tax calculator utilities
    "calculate_tax",
    "calculate_tax_for_items",
    "get_default_tax_rate",
    "get_tax_rate_for_listing",
    "get_tax_rate_for_category",
    "get_shipping_tax_rate",
    "is_b2b_tax_exempt",
    "calculate_b2b_tax",
    "get_tax_breakdown_for_invoice",
    "get_price_display",
    "format_tax_amount",
    "validate_tax_rate",
    "get_suggested_tax_rate",
    "TURKISH_VAT_RATES",
    # Seller payout utilities
    "credit_seller_for_order",
    "release_escrow_to_balance",
    "process_order_refund_from_balance",
    "calculate_commission",
    "get_payout_hold_days",
    "schedule_escrow_release",
    "process_escrow_release",
    "process_pending_escrow_releases",
    "on_sub_order_completed",
    "on_sub_order_refunded",
]
