
redis_cache: redis-server config/redis_cache.conf
redis_queue: redis-server config/redis_queue.conf


web: cd /home/ali/Masaüstü/İstoç\ Güncel\ Proje/Frappe_Mock_Data/Frappe_Marketplace/frappe-bench && bench serve --port 8080


socketio: /home/ali/.nvm/versions/node/v24.12.0/bin/node apps/frappe/socketio.js




schedule: cd /home/ali/Masaüstü/İstoç\ Güncel\ Proje/Frappe_Mock_Data/Frappe_Marketplace/frappe-bench && FRAPPE_SITE=marketplace.local bench schedule

worker:  cd /home/ali/Masaüstü/İstoç\ Güncel\ Proje/Frappe_Mock_Data/Frappe_Marketplace/frappe-bench && FRAPPE_SITE=marketplace.local bench worker 1>> logs/worker.log 2>> logs/worker.error.log

